[package]
name = "rustcord"
version = "0.1.0"
authors = ["pollen__"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.fltk]
fltk = "^0.16"

[dependencies.reqwest]
reqwest = "0.9.18"